import StoreProvider from "../StoreProvider"
import SessionWrapper from "../SesionProvider"
import NavbarComponent from "@/components/navbar/navbar"
  
export const metadata = {
  title: 'Computer Shop',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="flex flex-col w-full scrollbar-hide">
      <SessionWrapper>
        <body className="flex flex-col w-full min-h-screen">
          <StoreProvider>
            <header>
              <NavbarComponent/>
            </header>

            <main className="flex flex-grow h-full w-full justify-between">              
              <div className="w-full flex flex-grow items-start justify-center"> 
                  {children}
              </div>
              
            </main>
          </StoreProvider>
        </body>
      </SessionWrapper>
    </html>
  )
}
