import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComponent from "@/components/navbar/navbar";
import FooterComponent from "@/components/footer/footer";
import  StoreProvider  from "./StoreProvider";
import { AuthProvider } from "@/lib/context/context";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cambo Shop",
  description: "Generated by create next app",
  openGraph:{
      images:"https://img.favpng.com/6/5/12/ecommerce-logo-png-favpng-c9XwFQHwsmZeVNHU6BRWQgabB.jpg",
      description:"This is a project for the Computer Store."
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{
  return (
    <html lang="en">
       <body className={`${inter.className} `}>
        <AuthProvider>
          
          <StoreProvider>
            <header>
              <NavbarComponent/>
            </header>

            <main className="bg-slate-50 pb-9 ">
              {children}
            </main>
              
            <footer>
                <FooterComponent/>
            </footer>
          </StoreProvider>
       
        </AuthProvider>
        </body>
    </html>
  );
}
