import type { Metadata } from "next";
import "./globals.css";
import NavbarComponent from "@/components/navbar/navbar";
import FooterComponent from "@/components/footer/footer";
import  StoreProvider  from "./StoreProvider";
import { AuthProvider } from "@/lib/context/context";
import { ToastContainer } from "react-toastify";


export const metadata: Metadata = {
  title: "Cambo Shop",
  description: "Generated by create next app",
  openGraph:{
      images:"https://img.favpng  .com/6/5/12/ecommerce-logo-png-favpng-c9XwFQHwsmZeVNHU6BRWQgabB.jpg",
      description:"This is a project for the Computer Store."
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{
  return (
    <html lang="en">
       <body className={`flex flex-col`}>
        <AuthProvider>
          
          <StoreProvider>
            <header>
              <NavbarComponent/>
            </header>

            <main className="bg-slate-50 flex-1 ">
              {children}
            </main>
              
            <footer>
                <FooterComponent/>
            </footer>

             {/* Add ToastContainer here */}
             <ToastContainer
              position="top-center"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
            />
          </StoreProvider>
       
        </AuthProvider>
        </body>
    </html>
  );
}
